Repository llama-farm/llamafarm, pull requests merged in 2025-09, with the labels that each got.

#110 feat(designer): connect data component to api
  designer/src/api/datasets.ts
  designer/src/components/Data/Data.tsx
  designer/src/components/Data/DatasetView.tsx
  designer/src/hooks/useActiveProject.ts
  designer/src/hooks/useDatasets.ts
  designer/src/hooks/useProjectSwitchNavigation.ts
  designer/src/types/datasets.ts
  designer/src/types/index.ts
Labels: merge-when-approved

#132 chore: publish docker images during release
  .github/workflows/cli-installer.yml
  .github/workflows/cli.yml
  .github/workflows/release-cli.yml
  .github/workflows/release-docker.yml
  cli/hack/test-installer-docker.sh
  cli/hack/test-installer-quick.sh
Labels: merge-when-approved

#125 Feat add config code editor
  designer/dist/index.html
  designer/package-lock.json
  designer/package.json
  designer/src/Chat.tsx
  designer/src/components/CodeMirrorEditor/CodeMirrorEditor.tsx
  designer/src/components/CodeMirrorEditor/EditorContent.tsx
  designer/src/components/CodeMirrorEditor/EditorFallback.tsx
  designer/src/components/CodeMirrorEditor/EditorToolbar.tsx
  designer/src/components/ConfigEditor.tsx
  designer/src/components/ConfigEditor/ConfigEditor.tsx
  designer/src/components/ConfigEditor/ConfigError.tsx
  designer/src/components/ConfigEditor/ConfigLoading.tsx
  designer/src/components/Dashboard/Dashboard.tsx
  designer/src/components/Data/Data.tsx
  designer/src/components/Header.tsx
  designer/src/components/Prompt/Prompt.tsx
  designer/src/components/Test.tsx
  designer/src/hooks/useCodeMirror.ts
  designer/src/hooks/useFormattedConfig.ts
  designer/src/index.css
  designer/src/main.tsx
  designer/src/types/codemirror.d.ts
  designer/src/types/config.d.ts
  designer/tailwind.config.js
  designer/vite.config.ts
Labels: merge-when-approved

#138 feat(designer): packaging experience
  designer/src/App.tsx
  designer/src/assets/icons/Folder.tsx
  designer/src/common/FontIcon.tsx
  designer/src/components/Dashboard/Dashboard.tsx
  designer/src/components/Dashboard/Versions.tsx
  designer/src/components/Data/Data.tsx
  designer/src/components/Data/DatasetView.tsx
  designer/src/components/Models/Models.tsx
  designer/src/components/Prompt/GeneratedOutput/GeneratedOutputs.tsx
  designer/src/components/Prompt/Prompt.tsx
  designer/src/components/Rag/ChangeEmbeddingModel.tsx
  designer/src/components/Rag/ExtractionSettings.tsx
  designer/src/components/Rag/Rag.tsx
  designer/src/components/Rag/RetrievalMethod.tsx
  designer/src/components/Rag/StrategyView.tsx
  designer/src/components/Test.tsx
  designer/src/components/common/PageActions.tsx
  designer/src/components/ui/input.tsx
  designer/src/components/ui/textarea.tsx
  designer/src/contexts/PackageModalContext.tsx
  designer/src/main.tsx
Labels: merge-when-approved

#151 fix(designer): creating project experience was not working
  designer/src/App.tsx
  designer/src/Home.tsx
  designer/src/components/Dashboard/Dashboard.tsx
  designer/src/components/Header.tsx
  designer/src/components/Project/ProjectModal.tsx
  designer/src/components/Project/Projects.tsx
  designer/src/components/ui/dialog.tsx
  designer/src/contexts/ProjectModalContext.tsx
  designer/src/hooks/useProjectModal.ts
  designer/src/utils/projectConstants.ts
Labels: merge-when-approved

#145 feat(cli): run designer in background on `lf dev`
  .agents/commands/commit.md
  .agents/commands/github_issues.md
  .agents/commands/plan.md
  .agents/commands/research.md
  .agents/rules/cli.mdc
  .cursor/mcp.json
  .github/workflows/ci.yml
  AGENTS.md
  cli/cmd/chat_client.go
  cli/cmd/config/types_test.go
  cli/cmd/datasets.go
  cli/cmd/designer.go
  cli/cmd/designer_launcher.go
  cli/cmd/dev.go
  cli/cmd/docker_utils.go
  cli/cmd/init.go
  cli/cmd/projects.go
  cli/cmd/run.go
  cli/cmd/server_utils.go
  cli/cmd/server_utils_test.go
  cli/cmd/tui_chat.go
  cli/cmd/watcher.go
Labels: merge-when-approved

#170 fix: lf run project path + jsonschema validation error output
  cli/cmd/config/types_test.go
  cli/cmd/dev.go
  cli/cmd/run.go
  config/helpers/loader.py
Labels: merge-when-approved

#165 chore: add contribution directives
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: merge-when-approved

#196 Fix: Resolve Ollama integration issues and instructor mode configuration
  .gitignore
  cli/cmd/chat_client.go
  config/datamodel.py
  config/helpers/loader.py
  config/schema.yaml
  config/templates/advanced.yaml
  config/templates/default.yaml
  examples/rag_pipeline/llamafarm-example.yaml
  examples/rag_pipeline/test_rag_comprehensive.sh
  lf
  rag/schema.yaml
  server/agents/project_chat_orchestrator.py
  server/seeds/project_seed/llamafarm.yaml
  server/services/project_chat_service.py
  test/integration/test_rag_integration.sh
Labels: merge-when-approved

#152 feat(designer): client side session storage
  designer/src/Chat.tsx
  designer/src/Home.tsx
  designer/src/components/Chatbox/Chatbox.tsx
  designer/src/components/TestChat/TestChat.tsx
  designer/src/hooks/useChatSession.ts
  designer/src/hooks/useChatbox.ts
  designer/src/hooks/useChatboxWithProjectSession.ts
  designer/src/hooks/useProjectSession.ts
  designer/src/utils/homePageUtils.ts
  designer/src/utils/projectSessionManager.ts
Labels: merge-when-approved

#216 fix(cli): ensure project sync runs for required commands
  cli/cmd/datasets.go
  cli/cmd/models.go
  cli/cmd/rag_manage.go
  cli/cmd/rag_query.go
  cli/cmd/run.go
  server/services/rag_health_cache.py
Labels: merge-when-approved

#217 fix(rag): store data in proper location within project dir
  .github/workflows/docker.yml
  config/datamodel.py
  deployment/docker_compose/docker-compose.yml
  rag/README.md
  rag/api.py
  rag/celery_app.py
  rag/cli/README.md
  rag/components/embedders/huggingface_embedder/huggingface_embedder.py
  rag/components/embedders/ollama_embedder/ollama_embedder.py
  rag/components/embedders/openai_embedder/openai_embedder.py
  rag/components/embedders/sentence_transformer_embedder/sentence_transformer_embedder.py
  rag/components/retrievers/base.py
  rag/components/retrievers/basic_similarity/basic_similarity.py
  rag/components/retrievers/metadata_filtered/metadata_filtered.py
  rag/components/retrievers/multi_query/multi_query.py
  rag/components/retrievers/reranked/reranked.py
  rag/components/stores/chroma_store/chroma_store.md
  rag/components/stores/chroma_store/chroma_store.py
  rag/components/stores/chroma_store/defaults.yaml
  rag/components/stores/chroma_store/schema.yaml
  rag/components/stores/qdrant_store/qdrant_store.py
  rag/core/base.py
  rag/core/factories.py
  rag/core/ingest_handler.py
  rag/core/settings.py
  rag/docs/COMPONENTS.md
  rag/docs/SCHEMA.md
  rag/docs/STRATEGY_SYSTEM.md
  rag/main.py
  rag/pyproject.toml
  rag/schema.yaml
  rag/scripts/smart_schema_validator.py
  rag/scripts/update_all_components.py
  rag/tests/components/embedders/test_ollama_embedder.py
  rag/tests/components/stores/test_chroma_store.py
  rag/tests/test_core_modules.py
  rag/tests/test_stores.py
  rag/utils/path_resolver.py
  rag/uv.lock
  server/services/data_service.py
  server/tests/test_data_service.py
Labels: merge-when-approved

#225 fix(config): update default template
  config/templates/default.yaml
Labels: merge-when-approved

#222 fix(cli): Windows Docker volume mount path conversion
  cli/cmd/docker_orchestrator.go
  cli/cmd/server_utils.go
Labels: merge-when-approved, component::cli

#197 Sample projects
  .github/workflows/docker.yml
  designer/Dockerfile
  designer/src/App.tsx
  designer/src/Home.tsx
  designer/src/api/datasets.ts
  designer/src/components/Data/Data.tsx
  designer/src/components/Data/ImportSampleDatasetModal.tsx
  designer/src/components/Header.tsx
  designer/src/components/Samples/ImportSampleDataModal.tsx
  designer/src/components/Samples/ImportSampleProjectModal.tsx
  designer/src/components/Samples/SampleCard.tsx
  designer/src/components/Samples/SamplePreviewModal.tsx
  designer/src/components/Samples/SampleProjects.tsx
  designer/src/data/sampleProjects.ts
Labels: merge-when-approved

#229 feat(cli): update the cli command structure
  README.md
  cli/README.md
  cli/cmd/datasets.go
  cli/cmd/dev.go
  cli/cmd/rag.go
  cli/cmd/rag_manage.go
  cli/cmd/rag_stats.go
  cli/cmd/root.go
  cli/cmd/run.go
  examples/README.md
  examples/rag_pipeline/README.md
  examples/rag_pipeline/run_example.sh
  examples/rag_pipeline/test_rag_comprehensive.sh
  examples/validate_examples.sh
  rag/check_rag_tasks.sh
  test/README.md
  test/cli/test_lf_run_commands.sh
  test/cli/test_lf_run_quick.sh
  test/cli/verify_lf_run.sh
  test/integration/test_rag_integration.sh
  test/scripts/test_readme_examples.sh
Labels: merge-when-approved

#230 chore: sign and notify macos cli binaries during release
  .github/workflows/release-cli.yml
Labels: merge-when-approved

#238 chore(rag): sync schema removal of excludes
  cli/cmd/config/types.go
  config/datamodel.py
  config/templates/advanced.yaml
  config/templates/default.yaml
  config/tests/invalid_config.yaml
  config/tests/test_edge_cases.py
  examples/rag_pipeline/README.md
  examples/rag_pipeline/llamafarm-example.yaml
  rag/README.md
  rag/docs/PARSERS.md
  rag/docs/SCHEMA.md
  rag/docs/STRATEGY_SYSTEM.md
Labels: merge-when-approved

#233 feat: add flexible agent handlers for rag support
  cli/cmd/chat_client.go
  cli/cmd/chat_client_test.go
  cli/cmd/run.go
  cli/cmd/tui_chat.go
  config/datamodel.py
  config/schema.yaml
  config/templates/default.yaml
  designer/src/api/chatService.ts
  server/agents/agent.py
  server/agents/project_chat_orchestrator.py
  server/api/routers/inference/inference.py
  server/api/routers/inference/services.py
  server/api/routers/projects/projects.py
  server/api/routers/shared/response_utils.py
  server/main.py
  server/seeds/project_seed/llamafarm.yaml
  server/services/project_chat_service.py
  server/services/project_service.py
  server/tests/test_chat_api_baseline.py
  server/tests/test_project_chat_orchestrator.py
Labels: merge-when-approved

#242 fix(cli): set docker host mapping for linux
  cli/cmd/docker_utils.go
  cli/cmd/docker_utils_test.go
  cli/cmd/server_utils.go
  config/datamodel.py
  config/helpers/loader.py
  config/tests/test_url_replacement.py
  deployment/docker_compose/docker-compose.yml
  rag/api.py
  rag/celery_app.py
  rag/components/parsers/parser_factory.py
  rag/components/retrievers/basic_similarity/basic_similarity.py
  rag/core/factories.py
  rag/core/strategies/handler.py
  rag/pyproject.toml
  rag/tasks/health_tasks.py
  rag/tasks/query_tasks.py
  rag/tasks/search_tasks.py
  rag/tests/test_data/test_strategies.yaml
  rag/tests/test_strategies.py
  rag/uv.lock
  server/pyproject.toml
  server/uv.lock
Labels: merge-when-approved

#239 feat(designer): upgrade banner
  designer/src/App.tsx
  designer/src/Chat.tsx
  designer/src/Home.tsx
  designer/src/components/Header.tsx
  designer/src/components/common/UpgradeBanners.tsx
  designer/src/components/common/VersionDetailsDialog.tsx
  designer/src/hooks/useUpgradeAvailability.ts
  designer/src/utils/versionUtils.ts
Labels: merge-when-approved

#201 chore(main): release 0.0.5
  .release-please-manifest.json
  CHANGELOG.md
Labels: autorelease: pending
